name: Deploy Backend to Azure Functions

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package.json

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Deploy to Azure Functions (Production)
        if: github.ref == 'refs/heads/main'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME_PRODUCTION }}
          package: ./backend
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PRODUCTION }}

      - name: Deploy to Azure Functions (Dev)
        if: github.ref == 'refs/heads/dev'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME_DEV }}
          package: ./backend
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DEV }}
